version: 2.1
  
jobs:
  grade:
    docker:
      - image: continuumio/miniconda3:4.5.11

    working_directory: /tmp/repo
    steps:
      - checkout
      - run:
          name: Install grading dependencies
          command: |
            source activate base
            apt-get -y update 
            apt-get -y install gcc python3-dev
            pip install --upgrade pip
            pip install --progress-bar off --force-reinstall numpy==1.21.4 
            pip install --progress-bar off --force-reinstall matplotlib==3.5.2
            pip install --progress-bar off --force-reinstall matplotlib-inline==0.1.3
            pip install --progress-bar off ipython ipywidgets pandas mne cachetools pennprov pyqt5-sip install seaborn PyQt5 PySide2
            pip install --progress-bar off https://github.com/nteract/papermill/archive/master.zip
            pip install --progress-bar off git+https://github.com/ieeg-portal/ieegpy.git
            
      - run:
          name: Install course specific dependencies
          command: |
            source activate base
            [ -e environment.yml ] && conda env update --quiet -f environment.yml && conda clean -tipsy || echo nothing to do
      - run:
          name: "Prepare output directories"
          command: |
            mkdir -p notebooks/test
            
      - run:
          name: Execute test/ICA_example.ipynb
          command: |
            source activate base
            papermill --cwd python python/ICA_example.ipynb homework-graded.ipynb
            jupyter nbconvert --to html --stdout python/homework-graded.ipynb > notebooks/test/homework.html
  
      - store_artifacts:
          path: /tmp/repo/notebooks
          destination: notebooks

workflows:
  version: 2
  grade_me:
    jobs:
      - grade
