version: '2.1'
orbs:
  matlab: mathworks/matlab@0.4.0
jobs:
  build:
    machine:
      image: 'ubuntu-2204:2022.07.1'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: matlab/test/pipeline_test_clip_circleci.m
workflows:
  build:
    jobs:
      - build
