version: '2.1'
orbs:
  matlab: mathworks/matlab@0.11.0
jobs:
  build:
    machine:
      image: 'ubuntu-2204:2022.07.1'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: /matlab/test/pipeline_test_clip_circleci.m
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
      - store_test_results:
          path: test-results
workflows:
  build:
    jobs:
      - build
