version: '2.1'
orbs:
  matlab: mathworks/matlab@0.11.0
jobs:
  build:
    machine:
      image: 'ubuntu-2204:2022.07.1'
    steps:
      - checkout
      - matlab/install
      - run:
          name: prep
          command:
            mkdir -p test-results
      - matlab/run-build:
          tasks: test
workflows:
  build:
    jobs:
      - build
