# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  matlab:
    type: boolean
    default: false
  python:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node
      
orbs:
  python: circleci/python@2.0.3
  matlab: mathworks/matlab@0.11.0
  
jobs:
  trigger-workflows:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh
              
  build_python: # this can be any name you choose
    parameters:
        package_name:
          type: string
    docker:
      - image: cimg/python:3.10.4
    executor: python/default # use the default executor defined within the orb
    working_directory: ~/project/<< parameters.package_name >>
    
    environment:
      PYTHONPATH: ./python
    steps:
      - checkout
      - restore_cache:
          name: restore dependency cache
          keys:
            - deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - python/install-packages:
          pkg-manager: pip
      - save_cache:
          name: save dependency cache
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ./cache
      - run: echo -e $GPG_KEY | gpg --import --no-tty --batch --yes
      - run: gpg -o python/*_ieeglogin.bin --decrypt python/*_ieeglogin.bin.gpg
      - run: gpg --decrypt ~/project/python/*_ieeglogin.bin.gpg
      - run: ls ~/project/python
      - run:
          name: prep
          command:
            mkdir -p test-results
      - run:
          name: unit tests
          command:
            pytest --html=report.html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results  
          
  build_matlab:
    parameters:
        package_name:
          type: string
    working_directory: ~/project/<< parameters.package_name >>
    
    machine:
      image: 'ubuntu-2204:2022.07.1'
    steps:
      - checkout:
          path: ~/project
      - matlab/install  
      - run: echo -e $GPG_KEY | gpg --import --no-tty --batch --yes
      - run: ls ~/project/matlab
      - run: gpg -o ~/project/matlab/*_ieeglogin.bin --decrypt ~/project/matlab/*_ieeglogin.bin.gpg
      - run:
          name: prep
          command:
            mkdir -p test-results
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
        
workflows:
  version: 2
  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # Workflows defined for each package.

  python:
    when: << pipeline.parameters.python >>
    jobs:
      - build_python:
          name: build_python
          package_name: python

  matlab:
    when: << pipeline.parameters.matlab >>
    jobs:
      - build_matlab:
          name: build_matlab
          package_name: matlab
