version: 2.1

jobs:
  grade:
    docker:
      - image: continuumio/miniconda3:4.5.11

    working_directory: /tmp/repo
    steps:
      - checkout
      - run:
          name: Install grading dependencies
          command: |
            source activate base
            pip install --progress-bar off ipython ipywidgets
            pip install --progress-bar off https://github.com/nteract/papermill/archive/master.zip
      - run:
          name: Install course specific dependencies
          command: |
            source activate base
            [ -e environment.yml ] && conda env update --quiet -f environment.yml && conda clean -tipsy || echo nothing to do
      - run:
          name: "Prepare output directories"
          command: |
            mkdir -p notebooks/week1
            mkdir -p notebooks/week3
            
      - run:
          name: Execute week1/homework.ipynb
          command: |
            source activate base
            papermill --cwd week1 week1/homework.ipynb homework-graded.ipynb
            jupyter nbconvert --to html --stdout week1/homework-graded.ipynb > notebooks/week1/homework.html
      - run:
          name: Execute week3/homework.ipynb
          command: |
            source activate base
            papermill --cwd week3 week3/homework.ipynb homework-graded.ipynb
            jupyter nbconvert --to html --stdout week3/homework-graded.ipynb > notebooks/week3/homework.html
      
      - store_artifacts:
          path: /tmp/repo/notebooks
          destination: notebooks

workflows:
  version: 2
  grade_me:
    jobs:
      - grade
